		try {
			p1.close(null);
		} catch (CoreException e) {
			fail("Should not throw an exception");

		}
